import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:my_hostel/components/hostel_info.dart';
import 'package:my_hostel/components/landowner.dart';
import 'package:my_hostel/components/notification.dart';
import 'package:my_hostel/components/receipt_info.dart';
import 'package:my_hostel/components/room_details.dart';
import 'package:my_hostel/components/student.dart';
import 'package:my_hostel/components/transaction.dart';
import 'package:my_hostel/components/user.dart';

final StateProvider<bool> hasInitializedProvider =
    StateProvider((ref) => false);

final StateProvider<bool> isAStudent = StateProvider((ref) => true);

final StateProvider<bool> hasMessagesProvider = StateProvider((ref) => false);

final StateProvider<bool> hasNotificationProvider =
    StateProvider((ref) => false);

final StateProvider<Student> studentProvider = StateProvider(
  (ref) => Student(
    firstName: "John",
    lastName: "Doe",
    gender: "Male",
    image: "assets/images/watch man.jpg",
    id: "Info 4",
    level: 300,
    email: "johndoe@mail.com",
    location: "Kofesu",
    amount: 50000,
    available: true,
    origin: "Ebonyi",
    denomination: "Christ Apostolic Church",
    hobby: "Singing and dancing",
    ageRange: "21 - 25",
    religion: "Christianity",
    joined: DateTime.now(),
    searchAppearances: 19,
    profileViews: 48,
    collaboratedRoommates: 9,
    rentedHostels: 3,
    contact: "09012345678",
  ),
);

final StateProvider<Landowner> ownerProvider = StateProvider(
  (ref) => Landowner(
    dateJoined: DateTime.now(),
    firstName: "Smith",
    lastName: "Woods",
    gender: "Male",
    image: "assets/images/watch man.jpg",
    id: "Landowner",
    email: "landlord@mail.com",
    contact: "09012345678",
  ),
);

final StateProvider<int> dashboardTabIndexProvider = StateProvider((ref) => 0);

final StateProvider<List<HostelInfo>> acquiredHostelsProvider =
    StateProvider((ref) => [
          HostelInfo(
            id: "1",
            name: "Manchester Hostel Askj",
            image: "assets/images/street.jpg",
            bedrooms: 1,
            bathrooms: 1,
            area: 2500,
            price: 100000,
            address: "Harmony Estate",
            description:
                "Lorem ipsum dolor sit amet, consectetur. Nam utcurs usipsum dolor sit amet. "
                "Lorem ipsum dolor sit amet, consectetur.",
            rules: const [
              "Lorem ipsum dolor sit amet, consectetur.",
              "Nam utcurs usipsum dolor sit amet.",
              "Lorem ipsum dolor sit amet, consectetur.",
              "Nam utcurs usipsum dolor sit amet.",
              "Lorem ipsum dolor sit amet, consectetur. Nam utcurs usipsum dolor sit amet."
            ],
            hostelFacilities: const [
              "Light",
              "Water",
              "Security",
              "None",
              "Light",
              "Water",
              "Security",
            ],
            roomsLeft: const [
              RoomInfo(
                name: "Room 1",
                facilities: [
                  "Light",
                  "Water",
                  "Security",
                  "None",
                ],
                id: "Room 1 ID",
                media: [
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                ],
                price: 100000,
              ),
              RoomInfo(
                name: "Room 2",
                facilities: [
                  "Light",
                  "Water",
                  "Security",
                  "None",
                ],
                id: "Room 2 ID",
                media: [
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                ],
                price: 100000,
              ),
              RoomInfo(
                name: "Room 3",
                facilities: [
                  "Light",
                  "Water",
                  "Security",
                  "None",
                ],
                id: "Room 3 ID",
                media: [
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                ],
                price: 100000,
              ),
              RoomInfo(
                name: "Room 4",
                facilities: [
                  "Light",
                  "Water",
                  "Security",
                  "None",
                ],
                id: "Room 4 ID",
                media: [
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                ],
                price: 100000,
              ),
              RoomInfo(
                name: "Room 5",
                facilities: [
                  "Light",
                  "Water",
                  "Security",
                  "None",
                ],
                id: "Room 5 ID",
                media: [
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                ],
                price: 100000,
              )
            ],
            media: const [
              "assets/images/street.jpg",
              "assets/images/street.jpg",
              "assets/images/street.jpg",
              "assets/images/street.jpg",
              "assets/images/street.jpg",
              "assets/images/street.jpg",
              "assets/images/street.jpg",
              "assets/images/street.jpg",
              "assets/images/street.jpg",
            ],
            owner: Landowner(
              id: "12",
              image: "assets/images/watch man.jpg",
              lastName: "Julius",
              firstName: "Adeyemi",
              verified: true,
              ratings: 3.5,
              contact: "+2348012345678",
              totalRated: 234,
              dateJoined: DateTime.now(),
              address: "Ibadan, Nigeria",
            ),
          ),
          HostelInfo(
            id: "2",
            name: "Liverpool Hostel",
            image: "assets/images/street.jpg",
            bedrooms: 1,
            bathrooms: 1,
            area: 2500,
            price: 100000,
            address: "Harmony Estate",
            description:
                "Lorem ipsum dolor sit amet, consectetur. Nam utcurs usipsum dolor sit amet. "
                "Lorem ipsum dolor sit amet, consectetur.",
            rules: const [
              "Lorem ipsum dolor sit amet, consectetur.",
              "Nam utcurs usipsum dolor sit amet.",
              "Lorem ipsum dolor sit amet, consectetur.",
              "Nam utcurs usipsum dolor sit amet.",
              "Lorem ipsum dolor sit amet, consectetur. Nam utcurs usipsum dolor sit amet."
            ],
            roomsLeft: const [
              RoomInfo(
                name: "Room 1",
                facilities: [
                  "Light",
                  "Water",
                  "Security",
                  "None",
                ],
                id: "Room 1 ID",
                media: [
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                ],
                price: 100000,
              ),
              RoomInfo(
                name: "Room 2",
                facilities: [
                  "Light",
                  "Water",
                  "Security",
                  "None",
                ],
                id: "Room 2 ID",
                media: [
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                ],
                price: 100000,
              ),
              RoomInfo(
                name: "Room 3",
                facilities: [
                  "Light",
                  "Water",
                  "Security",
                  "None",
                ],
                id: "Room 3 ID",
                media: [
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                ],
                price: 100000,
              ),
              RoomInfo(
                name: "Room 4",
                facilities: [
                  "Light",
                  "Water",
                  "Security",
                  "None",
                ],
                id: "Room 4 ID",
                media: [
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                ],
                price: 100000,
              ),
              RoomInfo(
                name: "Room 5",
                facilities: [
                  "Light",
                  "Water",
                  "Security",
                  "None",
                ],
                id: "Room 5 ID",
                media: [
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                ],
                price: 100000,
              )
            ],
            hostelFacilities: const [
              "Light",
              "Water",
              "Security",
              "None",
              "Light",
              "Water",
              "Security",
            ],
            media: const [
              "assets/images/street.jpg",
              "assets/images/street.jpg",
              "assets/images/street.jpg",
              "assets/images/street.jpg",
              "assets/images/street.jpg",
              "assets/images/street.jpg",
              "assets/images/street.jpg",
              "assets/images/street.jpg",
              "assets/images/street.jpg",
            ],
            owner: Landowner(
              id: "12",
              image: "assets/images/watch man.jpg",
              lastName: "Julius",
              firstName: "Adeyemi",
              verified: true,
              ratings: 3.5,
              contact: "+2348012345678",
              totalRated: 234,
              dateJoined: DateTime.now(),
              address: "Ibadan, Nigeria",
            ),
          ),
          HostelInfo(
            id: "3",
            name: "Scotland",
            image: "assets/images/street.jpg",
            bedrooms: 1,
            bathrooms: 1,
            area: 2500,
            price: 100000,
            address: "Harmony Estate",
            description:
                "Lorem ipsum dolor sit amet, consectetur. Nam utcurs usipsum dolor sit amet. "
                "Lorem ipsum dolor sit amet, consectetur.",
            rules: const [
              "Lorem ipsum dolor sit amet, consectetur.",
              "Nam utcurs usipsum dolor sit amet.",
              "Lorem ipsum dolor sit amet, consectetur.",
              "Nam utcurs usipsum dolor sit amet.",
              "Lorem ipsum dolor sit amet, consectetur. Nam utcurs usipsum dolor sit amet."
            ],
            hostelFacilities: const [
              "Light",
              "Water",
              "Security",
              "None",
              "Light",
              "Water",
              "Security",
            ],
            roomsLeft: const [
              RoomInfo(
                name: "Room 1",
                facilities: [
                  "Light",
                  "Water",
                  "Security",
                  "None",
                ],
                id: "Room 1 ID",
                media: [
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                ],
                price: 100000,
              ),
              RoomInfo(
                name: "Room 2",
                facilities: [
                  "Light",
                  "Water",
                  "Security",
                  "None",
                ],
                id: "Room 2 ID",
                media: [
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                ],
                price: 100000,
              ),
              RoomInfo(
                name: "Room 3",
                facilities: [
                  "Light",
                  "Water",
                  "Security",
                  "None",
                ],
                id: "Room 3 ID",
                media: [
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                ],
                price: 100000,
              ),
              RoomInfo(
                name: "Room 4",
                facilities: [
                  "Light",
                  "Water",
                  "Security",
                  "None",
                ],
                id: "Room 4 ID",
                media: [
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                ],
                price: 100000,
              ),
              RoomInfo(
                name: "Room 5",
                facilities: [
                  "Light",
                  "Water",
                  "Security",
                  "None",
                ],
                id: "Room 5 ID",
                media: [
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                ],
                price: 100000,
              )
            ],
            media: const [
              "assets/images/street.jpg",
              "assets/images/street.jpg",
              "assets/images/street.jpg",
              "assets/images/street.jpg",
              "assets/images/street.jpg",
              "assets/images/street.jpg",
              "assets/images/street.jpg",
              "assets/images/street.jpg",
              "assets/images/street.jpg",
            ],
            owner: Landowner(
              id: "12",
              image: "assets/images/watch man.jpg",
              lastName: "Julius",
              firstName: "Adeyemi",
              verified: true,
              ratings: 3.5,
              contact: "+2348012345678",
              totalRated: 234,
              dateJoined: DateTime.now(),
              address: "Ibadan, Nigeria",
            ),
          ),
          HostelInfo(
            id: "4",
            name: "Grace Ville",
            image: "assets/images/street.jpg",
            bedrooms: 1,
            bathrooms: 1,
            area: 2500,
            price: 100000,
            address: "Harmony Estate",
            description:
                "Lorem ipsum dolor sit amet, consectetur. Nam utcurs usipsum dolor sit amet. "
                "Lorem ipsum dolor sit amet, consectetur.",
            rules: const [
              "Lorem ipsum dolor sit amet, consectetur.",
              "Nam utcurs usipsum dolor sit amet.",
              "Lorem ipsum dolor sit amet, consectetur.",
              "Nam utcurs usipsum dolor sit amet.",
              "Lorem ipsum dolor sit amet, consectetur. Nam utcurs usipsum dolor sit amet."
            ],
            hostelFacilities: const [
              "Light",
              "Water",
              "Security",
              "None",
              "Light",
              "Water",
              "Security",
            ],
            roomsLeft: const [
              RoomInfo(
                name: "Room 1",
                facilities: [
                  "Light",
                  "Water",
                  "Security",
                  "None",
                ],
                id: "Room 1 ID",
                media: [
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                ],
                price: 100000,
              ),
              RoomInfo(
                name: "Room 2",
                facilities: [
                  "Light",
                  "Water",
                  "Security",
                  "None",
                ],
                id: "Room 2 ID",
                media: [
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                ],
                price: 100000,
              ),
              RoomInfo(
                name: "Room 3",
                facilities: [
                  "Light",
                  "Water",
                  "Security",
                  "None",
                ],
                id: "Room 3 ID",
                media: [
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                ],
                price: 100000,
              ),
              RoomInfo(
                name: "Room 4",
                facilities: [
                  "Light",
                  "Water",
                  "Security",
                  "None",
                ],
                id: "Room 4 ID",
                media: [
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                ],
                price: 100000,
              ),
              RoomInfo(
                name: "Room 5",
                facilities: [
                  "Light",
                  "Water",
                  "Security",
                  "None",
                ],
                id: "Room 5 ID",
                media: [
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                ],
                price: 100000,
              )
            ],
            media: const [
              "assets/images/street.jpg",
              "assets/images/street.jpg",
              "assets/images/street.jpg",
              "assets/images/street.jpg",
              "assets/images/street.jpg",
              "assets/images/street.jpg",
              "assets/images/street.jpg",
              "assets/images/street.jpg",
              "assets/images/street.jpg",
            ],
            owner: Landowner(
              id: "12",
              image: "assets/images/watch man.jpg",
              lastName: "Julius",
              firstName: "Adeyemi",
              verified: true,
              ratings: 3.5,
              contact: "+2348012345678",
              totalRated: 234,
              dateJoined: DateTime.now(),
              address: "Ibadan, Nigeria",
            ),
          )
        ]);

final StateProvider<List<Student>> acquiredRoommatesProvider =
    StateProvider((ref) {
  return [
    Student(
      firstName: "John",
      lastName: "Doe",
      gender: "Male",
      image: "assets/images/watch man.jpg",
      id: "Info 1",
      level: 100,
      location: "Harmony",
      amount: 50000,
      available: true,
      origin: "Ebonyi",
      denomination: "Christ Apostolic Church",
      hobby: "Singing and dancing",
      ageRange: "23 - 30",
      religion: "Christianity",
      joined: DateTime.now(),
    ),
    Student(
      firstName: "John",
      lastName: "Doe",
      gender: "Male",
      image: "assets/images/watch man.jpg",
      id: "Info 2",
      level: 300,
      location: "Isolu",
      amount: 75000,
      available: true,
      origin: "Ebonyi",
      denomination: "Christ Apostolic Church",
      hobby: "Singing and dancing",
      ageRange: "23 - 30",
      religion: "Christianity",
      joined: DateTime.now(),
    ),
    Student(
      firstName: "John",
      lastName: "Doe",
      gender: "Male",
      image: "assets/images/watch man.jpg",
      id: "Info 3",
      level: 200,
      location: "Accord",
      amount: 50000,
      available: false,
      origin: "Ebonyi",
      denomination: "Christ Apostolic Church",
      hobby: "Singing and dancing",
      ageRange: "23 - 30",
      religion: "Christianity",
      joined: DateTime.now(),
    ),
    Student(
      firstName: "John",
      lastName: "Doe",
      gender: "Male",
      image: "assets/images/watch man.jpg",
      id: "Info 4",
      level: 500,
      location: "Kofesu",
      amount: 40000,
      available: false,
      origin: "Ebonyi",
      denomination: "Christ Apostolic Church",
      hobby: "Singing and dancing",
      ageRange: "23 - 30",
      religion: "Christianity",
      joined: DateTime.now(),
    )
  ];
});

final StateProvider<List<HostelInfo>> availableHostelsProvider =
    StateProvider((ref) => [
          HostelInfo(
            id: "11",
            name: "Manchester Hostel Askj",
            image: "assets/images/street.jpg",
            bedrooms: 1,
            bathrooms: 1,
            area: 2500,
            price: 100000,
            address: "Harmony Estate",
            description:
                "Lorem ipsum dolor sit amet, consectetur. Nam utcurs usipsum dolor sit amet. "
                "Lorem ipsum dolor sit amet, consectetur.",
            rules: const [
              "Lorem ipsum dolor sit amet, consectetur.",
              "Nam utcurs usipsum dolor sit amet.",
              "Lorem ipsum dolor sit amet, consectetur.",
              "Nam utcurs usipsum dolor sit amet.",
              "Lorem ipsum dolor sit amet, consectetur. Nam utcurs usipsum dolor sit amet."
            ],
            hostelFacilities: const [
              "Light",
              "Water",
              "Security",
              "None",
              "Light",
              "Water",
              "Security",
            ],
            roomsLeft: const [
              RoomInfo(
                name: "Room 1",
                facilities: [
                  "Light",
                  "Water",
                  "Security",
                  "None",
                ],
                id: "Room 1 ID",
                media: [
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                ],
                price: 100000,
              ),
              RoomInfo(
                name: "Room 2",
                facilities: [
                  "Light",
                  "Water",
                  "Security",
                  "None",
                ],
                id: "Room 2 ID",
                media: [
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                ],
                price: 100000,
              ),
              RoomInfo(
                name: "Room 3",
                facilities: [
                  "Light",
                  "Water",
                  "Security",
                  "None",
                ],
                id: "Room 3 ID",
                media: [
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                ],
                price: 100000,
              ),
              RoomInfo(
                name: "Room 4",
                facilities: [
                  "Light",
                  "Water",
                  "Security",
                  "None",
                ],
                id: "Room 4 ID",
                media: [
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                ],
                price: 100000,
              ),
              RoomInfo(
                name: "Room 5",
                facilities: [
                  "Light",
                  "Water",
                  "Security",
                  "None",
                ],
                id: "Room 5 ID",
                media: [
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                ],
                price: 100000,
              )
            ],
            media: const [
              "assets/images/street.jpg",
              "assets/images/street.jpg",
              "assets/images/street.jpg",
              "assets/images/street.jpg",
              "assets/images/street.jpg",
              "assets/images/street.jpg",
              "assets/images/street.jpg",
              "assets/images/street.jpg",
              "assets/images/street.jpg",
            ],
            owner: Landowner(
              id: "12",
              image: "assets/images/watch man.jpg",
              lastName: "Julius",
              firstName: "Adeyemi",
              verified: true,
              ratings: 3.5,
              contact: "+2348012345678",
              totalRated: 234,
              dateJoined: DateTime.now(),
              address: "Ibadan, Nigeria",
            ),
          ),
          HostelInfo(
            id: "12",
            name: "Liverpool Hostel",
            image: "assets/images/street.jpg",
            bedrooms: 1,
            bathrooms: 1,
            area: 2500,
            price: 100000,
            address: "Harmony Estate",
            description:
                "Lorem ipsum dolor sit amet, consectetur. Nam utcurs usipsum dolor sit amet. "
                "Lorem ipsum dolor sit amet, consectetur.",
            rules: const [
              "Lorem ipsum dolor sit amet, consectetur.",
              "Nam utcurs usipsum dolor sit amet.",
              "Lorem ipsum dolor sit amet, consectetur.",
              "Nam utcurs usipsum dolor sit amet.",
              "Lorem ipsum dolor sit amet, consectetur. Nam utcurs usipsum dolor sit amet."
            ],
            roomsLeft: const [
              RoomInfo(
                name: "Room 1",
                facilities: [
                  "Light",
                  "Water",
                  "Security",
                  "None",
                ],
                id: "Room 1 ID",
                media: [
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                ],
                price: 100000,
              ),
              RoomInfo(
                name: "Room 2",
                facilities: [
                  "Light",
                  "Water",
                  "Security",
                  "None",
                ],
                id: "Room 2 ID",
                media: [
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                ],
                price: 100000,
              ),
              RoomInfo(
                name: "Room 3",
                facilities: [
                  "Light",
                  "Water",
                  "Security",
                  "None",
                ],
                id: "Room 3 ID",
                media: [
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                ],
                price: 100000,
              ),
              RoomInfo(
                name: "Room 4",
                facilities: [
                  "Light",
                  "Water",
                  "Security",
                  "None",
                ],
                id: "Room 4 ID",
                media: [
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                ],
                price: 100000,
              ),
              RoomInfo(
                name: "Room 5",
                facilities: [
                  "Light",
                  "Water",
                  "Security",
                  "None",
                ],
                id: "Room 5 ID",
                media: [
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                ],
                price: 100000,
              )
            ],
            hostelFacilities: const [
              "Light",
              "Water",
              "Security",
              "None",
              "Light",
              "Water",
              "Security",
            ],
            media: const [
              "assets/images/street.jpg",
              "assets/images/street.jpg",
              "assets/images/street.jpg",
              "assets/images/street.jpg",
              "assets/images/street.jpg",
              "assets/images/street.jpg",
              "assets/images/street.jpg",
              "assets/images/street.jpg",
              "assets/images/street.jpg",
            ],
            owner: Landowner(
              id: "12",
              image: "assets/images/watch man.jpg",
              lastName: "Julius",
              firstName: "Adeyemi",
              verified: true,
              ratings: 3.5,
              contact: "+2348012345678",
              totalRated: 234,
              dateJoined: DateTime.now(),
              address: "Ibadan, Nigeria",
            ),
          ),
          HostelInfo(
            id: "13",
            name: "Scotland",
            image: "assets/images/street.jpg",
            bedrooms: 1,
            bathrooms: 1,
            area: 2500,
            price: 100000,
            address: "Harmony Estate",
            description:
                "Lorem ipsum dolor sit amet, consectetur. Nam utcurs usipsum dolor sit amet. "
                "Lorem ipsum dolor sit amet, consectetur.",
            rules: const [
              "Lorem ipsum dolor sit amet, consectetur.",
              "Nam utcurs usipsum dolor sit amet.",
              "Lorem ipsum dolor sit amet, consectetur.",
              "Nam utcurs usipsum dolor sit amet.",
              "Lorem ipsum dolor sit amet, consectetur. Nam utcurs usipsum dolor sit amet."
            ],
            roomsLeft: const [
              RoomInfo(
                name: "Room 1",
                facilities: [
                  "Light",
                  "Water",
                  "Security",
                  "None",
                ],
                id: "Room 1 ID",
                media: [
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                ],
                price: 100000,
              ),
              RoomInfo(
                name: "Room 2",
                facilities: [
                  "Light",
                  "Water",
                  "Security",
                  "None",
                ],
                id: "Room 2 ID",
                media: [
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                ],
                price: 100000,
              ),
              RoomInfo(
                name: "Room 3",
                facilities: [
                  "Light",
                  "Water",
                  "Security",
                  "None",
                ],
                id: "Room 3 ID",
                media: [
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                ],
                price: 100000,
              ),
              RoomInfo(
                name: "Room 4",
                facilities: [
                  "Light",
                  "Water",
                  "Security",
                  "None",
                ],
                id: "Room 4 ID",
                media: [
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                ],
                price: 100000,
              ),
              RoomInfo(
                name: "Room 5",
                facilities: [
                  "Light",
                  "Water",
                  "Security",
                  "None",
                ],
                id: "Room 5 ID",
                media: [
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                ],
                price: 100000,
              )
            ],
            hostelFacilities: const [
              "Light",
              "Water",
              "Security",
              "None",
              "Light",
              "Water",
              "Security",
            ],
            media: const [
              "assets/images/street.jpg",
              "assets/images/street.jpg",
              "assets/images/street.jpg",
              "assets/images/street.jpg",
              "assets/images/street.jpg",
              "assets/images/street.jpg",
              "assets/images/street.jpg",
              "assets/images/street.jpg",
              "assets/images/street.jpg",
            ],
            owner: Landowner(
              id: "12",
              image: "assets/images/watch man.jpg",
              lastName: "Julius",
              firstName: "Adeyemi",
              verified: true,
              ratings: 3.5,
              contact: "+2348012345678",
              totalRated: 234,
              dateJoined: DateTime.now(),
              address: "Ibadan, Nigeria",
            ),
          ),
          HostelInfo(
            id: "14",
            name: "Grace Ville",
            image: "assets/images/street.jpg",
            bedrooms: 1,
            bathrooms: 1,
            area: 2500,
            price: 100000,
            address: "Harmony Estate",
            description:
                "Lorem ipsum dolor sit amet, consectetur. Nam utcurs usipsum dolor sit amet. "
                "Lorem ipsum dolor sit amet, consectetur.",
            rules: const [
              "Lorem ipsum dolor sit amet, consectetur.",
              "Nam utcurs usipsum dolor sit amet.",
              "Lorem ipsum dolor sit amet, consectetur.",
              "Nam utcurs usipsum dolor sit amet.",
              "Lorem ipsum dolor sit amet, consectetur. Nam utcurs usipsum dolor sit amet."
            ],
            roomsLeft: const [
              RoomInfo(
                name: "Room 1",
                facilities: [
                  "Light",
                  "Water",
                  "Security",
                  "None",
                ],
                id: "Room 1 ID",
                media: [
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                ],
                price: 100000,
              ),
              RoomInfo(
                name: "Room 2",
                facilities: [
                  "Light",
                  "Water",
                  "Security",
                  "None",
                ],
                id: "Room 2 ID",
                media: [
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                ],
                price: 100000,
              ),
              RoomInfo(
                name: "Room 3",
                facilities: [
                  "Light",
                  "Water",
                  "Security",
                  "None",
                ],
                id: "Room 3 ID",
                media: [
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                ],
                price: 100000,
              ),
              RoomInfo(
                name: "Room 4",
                facilities: [
                  "Light",
                  "Water",
                  "Security",
                  "None",
                ],
                id: "Room 4 ID",
                media: [
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                ],
                price: 100000,
              ),
              RoomInfo(
                name: "Room 5",
                facilities: [
                  "Light",
                  "Water",
                  "Security",
                  "None",
                ],
                id: "Room 5 ID",
                media: [
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                ],
                price: 100000,
              )
            ],
            hostelFacilities: const [
              "Light",
              "Water",
              "Security",
              "None",
              "Light",
              "Water",
              "Security",
            ],
            media: const [
              "assets/images/street.jpg",
              "assets/images/street.jpg",
              "assets/images/street.jpg",
              "assets/images/street.jpg",
              "assets/images/street.jpg",
              "assets/images/street.jpg",
              "assets/images/street.jpg",
              "assets/images/street.jpg",
              "assets/images/street.jpg",
            ],
            owner: Landowner(
              id: "12",
              image: "assets/images/watch man.jpg",
              lastName: "Julius",
              firstName: "Adeyemi",
              verified: true,
              ratings: 3.5,
              contact: "+2348012345678",
              totalRated: 234,
              dateJoined: DateTime.now(),
              address: "Ibadan, Nigeria",
            ),
          )
        ]);

final StateProvider<List<HostelInfo>> ownerHostelsProvider = StateProvider(
  (ref) => [
    HostelInfo(
      id: "11",
      name: "Manchester Hostel Askj",
      image: "assets/images/street.jpg",
      bedrooms: 1,
      bathrooms: 1,
      area: 2500,
      price: 100000,
      address: "Harmony Estate",
      description:
          "Lorem ipsum dolor sit amet, consectetur. Nam utcurs usipsum dolor sit amet. "
          "Lorem ipsum dolor sit amet, consectetur.",
      rules: const [
        "Lorem ipsum dolor sit amet, consectetur.",
        "Nam utcurs usipsum dolor sit amet.",
        "Lorem ipsum dolor sit amet, consectetur.",
        "Nam utcurs usipsum dolor sit amet.",
        "Lorem ipsum dolor sit amet, consectetur. Nam utcurs usipsum dolor sit amet."
      ],
      hostelFacilities: const [
        "Light",
        "Water",
        "Security",
        "None",
        "Light",
        "Water",
        "Security",
      ],
      roomsLeft: const [
        RoomInfo(
          name: "Room 1",
          facilities: [
            "Light",
            "Water",
            "Security",
            "None",
          ],
          id: "Room 1 ID",
          media: [
            "assets/images/street.jpg",
            "assets/images/street.jpg",
            "assets/images/street.jpg",
            "assets/images/street.jpg",
            "assets/images/street.jpg",
          ],
          price: 100000,
        ),
        RoomInfo(
          name: "Room 2",
          facilities: [
            "Light",
            "Water",
            "Security",
            "None",
          ],
          id: "Room 2 ID",
          media: [
            "assets/images/street.jpg",
            "assets/images/street.jpg",
            "assets/images/street.jpg",
            "assets/images/street.jpg",
            "assets/images/street.jpg",
          ],
          price: 100000,
        ),
        RoomInfo(
          name: "Room 3",
          facilities: [
            "Light",
            "Water",
            "Security",
            "None",
          ],
          id: "Room 3 ID",
          media: [
            "assets/images/street.jpg",
            "assets/images/street.jpg",
            "assets/images/street.jpg",
            "assets/images/street.jpg",
            "assets/images/street.jpg",
          ],
          price: 100000,
        ),
        RoomInfo(
          name: "Room 4",
          facilities: [
            "Light",
            "Water",
            "Security",
            "None",
          ],
          id: "Room 4 ID",
          media: [
            "assets/images/street.jpg",
            "assets/images/street.jpg",
            "assets/images/street.jpg",
            "assets/images/street.jpg",
            "assets/images/street.jpg",
          ],
          price: 100000,
        ),
        RoomInfo(
          name: "Room 5",
          facilities: [
            "Light",
            "Water",
            "Security",
            "None",
          ],
          id: "Room 5 ID",
          media: [
            "assets/images/street.jpg",
            "assets/images/street.jpg",
            "assets/images/street.jpg",
            "assets/images/street.jpg",
            "assets/images/street.jpg",
          ],
          price: 100000,
        )
      ],
      media: const [
        "assets/images/street.jpg",
        "assets/images/street.jpg",
        "assets/images/street.jpg",
        "assets/images/street.jpg",
        "assets/images/street.jpg",
        "assets/images/street.jpg",
        "assets/images/street.jpg",
        "assets/images/street.jpg",
        "assets/images/street.jpg",
      ],
      owner: ref.watch(ownerProvider),
    ),
    HostelInfo(
      id: "12",
      name: "Liverpool Hostel",
      image: "assets/images/street.jpg",
      bedrooms: 1,
      bathrooms: 1,
      area: 2500,
      price: 100000,
      address: "Harmony Estate",
      description:
          "Lorem ipsum dolor sit amet, consectetur. Nam utcurs usipsum dolor sit amet. "
          "Lorem ipsum dolor sit amet, consectetur.",
      rules: const [
        "Lorem ipsum dolor sit amet, consectetur.",
        "Nam utcurs usipsum dolor sit amet.",
        "Lorem ipsum dolor sit amet, consectetur.",
        "Nam utcurs usipsum dolor sit amet.",
        "Lorem ipsum dolor sit amet, consectetur. Nam utcurs usipsum dolor sit amet."
      ],
      roomsLeft: const [
        RoomInfo(
          name: "Room 1",
          facilities: [
            "Light",
            "Water",
            "Security",
            "None",
          ],
          id: "Room 1 ID",
          media: [
            "assets/images/street.jpg",
            "assets/images/street.jpg",
            "assets/images/street.jpg",
            "assets/images/street.jpg",
            "assets/images/street.jpg",
          ],
          price: 100000,
        ),
        RoomInfo(
          name: "Room 2",
          facilities: [
            "Light",
            "Water",
            "Security",
            "None",
          ],
          id: "Room 2 ID",
          media: [
            "assets/images/street.jpg",
            "assets/images/street.jpg",
            "assets/images/street.jpg",
            "assets/images/street.jpg",
            "assets/images/street.jpg",
          ],
          price: 100000,
        ),
        RoomInfo(
          name: "Room 3",
          facilities: [
            "Light",
            "Water",
            "Security",
            "None",
          ],
          id: "Room 3 ID",
          media: [
            "assets/images/street.jpg",
            "assets/images/street.jpg",
            "assets/images/street.jpg",
            "assets/images/street.jpg",
            "assets/images/street.jpg",
          ],
          price: 100000,
        ),
        RoomInfo(
          name: "Room 4",
          facilities: [
            "Light",
            "Water",
            "Security",
            "None",
          ],
          id: "Room 4 ID",
          media: [
            "assets/images/street.jpg",
            "assets/images/street.jpg",
            "assets/images/street.jpg",
            "assets/images/street.jpg",
            "assets/images/street.jpg",
          ],
          price: 100000,
        ),
        RoomInfo(
          name: "Room 5",
          facilities: [
            "Light",
            "Water",
            "Security",
            "None",
          ],
          id: "Room 5 ID",
          media: [
            "assets/images/street.jpg",
            "assets/images/street.jpg",
            "assets/images/street.jpg",
            "assets/images/street.jpg",
            "assets/images/street.jpg",
          ],
          price: 100000,
        )
      ],
      hostelFacilities: const [
        "Light",
        "Water",
        "Security",
        "None",
        "Light",
        "Water",
        "Security",
      ],
      media: const [
        "assets/images/street.jpg",
        "assets/images/street.jpg",
        "assets/images/street.jpg",
        "assets/images/street.jpg",
        "assets/images/street.jpg",
        "assets/images/street.jpg",
        "assets/images/street.jpg",
        "assets/images/street.jpg",
        "assets/images/street.jpg",
      ],
      owner: ref.watch(ownerProvider),
    ),
    HostelInfo(
      id: "13",
      name: "Scotland",
      image: "assets/images/street.jpg",
      bedrooms: 1,
      bathrooms: 1,
      area: 2500,
      price: 100000,
      address: "Harmony Estate",
      description:
          "Lorem ipsum dolor sit amet, consectetur. Nam utcurs usipsum dolor sit amet. "
          "Lorem ipsum dolor sit amet, consectetur.",
      rules: const [
        "Lorem ipsum dolor sit amet, consectetur.",
        "Nam utcurs usipsum dolor sit amet.",
        "Lorem ipsum dolor sit amet, consectetur.",
        "Nam utcurs usipsum dolor sit amet.",
        "Lorem ipsum dolor sit amet, consectetur. Nam utcurs usipsum dolor sit amet."
      ],
      roomsLeft: const [
        RoomInfo(
          name: "Room 1",
          facilities: [
            "Light",
            "Water",
            "Security",
            "None",
          ],
          id: "Room 1 ID",
          media: [
            "assets/images/street.jpg",
            "assets/images/street.jpg",
            "assets/images/street.jpg",
            "assets/images/street.jpg",
            "assets/images/street.jpg",
          ],
          price: 100000,
        ),
        RoomInfo(
          name: "Room 2",
          facilities: [
            "Light",
            "Water",
            "Security",
            "None",
          ],
          id: "Room 2 ID",
          media: [
            "assets/images/street.jpg",
            "assets/images/street.jpg",
            "assets/images/street.jpg",
            "assets/images/street.jpg",
            "assets/images/street.jpg",
          ],
          price: 100000,
        ),
        RoomInfo(
          name: "Room 3",
          facilities: [
            "Light",
            "Water",
            "Security",
            "None",
          ],
          id: "Room 3 ID",
          media: [
            "assets/images/street.jpg",
            "assets/images/street.jpg",
            "assets/images/street.jpg",
            "assets/images/street.jpg",
            "assets/images/street.jpg",
          ],
          price: 100000,
        ),
        RoomInfo(
          name: "Room 4",
          facilities: [
            "Light",
            "Water",
            "Security",
            "None",
          ],
          id: "Room 4 ID",
          media: [
            "assets/images/street.jpg",
            "assets/images/street.jpg",
            "assets/images/street.jpg",
            "assets/images/street.jpg",
            "assets/images/street.jpg",
          ],
          price: 100000,
        ),
        RoomInfo(
          name: "Room 5",
          facilities: [
            "Light",
            "Water",
            "Security",
            "None",
          ],
          id: "Room 5 ID",
          media: [
            "assets/images/street.jpg",
            "assets/images/street.jpg",
            "assets/images/street.jpg",
            "assets/images/street.jpg",
            "assets/images/street.jpg",
          ],
          price: 100000,
        )
      ],
      hostelFacilities: const [
        "Light",
        "Water",
        "Security",
        "None",
        "Light",
        "Water",
        "Security",
      ],
      media: const [
        "assets/images/street.jpg",
        "assets/images/street.jpg",
        "assets/images/street.jpg",
        "assets/images/street.jpg",
        "assets/images/street.jpg",
        "assets/images/street.jpg",
        "assets/images/street.jpg",
        "assets/images/street.jpg",
        "assets/images/street.jpg",
      ],
      owner: ref.watch(ownerProvider),
    ),
    HostelInfo(
      id: "14",
      name: "Grace Ville",
      image: "assets/images/street.jpg",
      bedrooms: 1,
      bathrooms: 1,
      area: 2500,
      price: 100000,
      address: "Harmony Estate",
      description:
          "Lorem ipsum dolor sit amet, consectetur. Nam utcurs usipsum dolor sit amet. "
          "Lorem ipsum dolor sit amet, consectetur.",
      rules: const [
        "Lorem ipsum dolor sit amet, consectetur.",
        "Nam utcurs usipsum dolor sit amet.",
        "Lorem ipsum dolor sit amet, consectetur.",
        "Nam utcurs usipsum dolor sit amet.",
        "Lorem ipsum dolor sit amet, consectetur. Nam utcurs usipsum dolor sit amet."
      ],
      roomsLeft: const [
        RoomInfo(
          name: "Room 1",
          facilities: [
            "Light",
            "Water",
            "Security",
            "None",
          ],
          id: "Room 1 ID",
          media: [
            "assets/images/street.jpg",
            "assets/images/street.jpg",
            "assets/images/street.jpg",
            "assets/images/street.jpg",
            "assets/images/street.jpg",
          ],
          price: 100000,
        ),
        RoomInfo(
          name: "Room 2",
          facilities: [
            "Light",
            "Water",
            "Security",
            "None",
          ],
          id: "Room 2 ID",
          media: [
            "assets/images/street.jpg",
            "assets/images/street.jpg",
            "assets/images/street.jpg",
            "assets/images/street.jpg",
            "assets/images/street.jpg",
          ],
          price: 100000,
        ),
        RoomInfo(
          name: "Room 3",
          facilities: [
            "Light",
            "Water",
            "Security",
            "None",
          ],
          id: "Room 3 ID",
          media: [
            "assets/images/street.jpg",
            "assets/images/street.jpg",
            "assets/images/street.jpg",
            "assets/images/street.jpg",
            "assets/images/street.jpg",
          ],
          price: 100000,
        ),
        RoomInfo(
          name: "Room 4",
          facilities: [
            "Light",
            "Water",
            "Security",
            "None",
          ],
          id: "Room 4 ID",
          media: [
            "assets/images/street.jpg",
            "assets/images/street.jpg",
            "assets/images/street.jpg",
            "assets/images/street.jpg",
            "assets/images/street.jpg",
          ],
          price: 100000,
        ),
        RoomInfo(
          name: "Room 5",
          facilities: [
            "Light",
            "Water",
            "Security",
            "None",
          ],
          id: "Room 5 ID",
          media: [
            "assets/images/street.jpg",
            "assets/images/street.jpg",
            "assets/images/street.jpg",
            "assets/images/street.jpg",
            "assets/images/street.jpg",
          ],
          price: 100000,
        )
      ],
      hostelFacilities: const [
        "Light",
        "Water",
        "Security",
        "None",
        "Light",
        "Water",
        "Security",
      ],
      media: const [
        "assets/images/street.jpg",
        "assets/images/street.jpg",
        "assets/images/street.jpg",
        "assets/images/street.jpg",
        "assets/images/street.jpg",
        "assets/images/street.jpg",
        "assets/images/street.jpg",
        "assets/images/street.jpg",
        "assets/images/street.jpg",
      ],
      owner: ref.watch(ownerProvider),
    )
  ],
);

final StateProvider<List<Student>> availableRoommatesProvider =
    StateProvider((ref) {
  return [
    Student(
      firstName: "John",
      lastName: "Doe",
      gender: "Male",
      image: "assets/images/watch man.jpg",
      id: "Info 11",
      level: 100,
      location: "Harmony",
      amount: 50000,
      available: true,
      origin: "Ebonyi",
      denomination: "Christ Apostolic Church",
      hobby: "Singing and dancing",
      ageRange: "23 - 30",
      religion: "Christianity",
      joined: DateTime.now(),
    ),
    Student(
      firstName: "John",
      lastName: "Doe",
      gender: "Male",
      image: "assets/images/watch man.jpg",
      id: "Info 12",
      level: 300,
      location: "Isolu",
      amount: 75000,
      available: true,
      origin: "Ebonyi",
      denomination: "Christ Apostolic Church",
      hobby: "Singing and dancing",
      ageRange: "23 - 30",
      religion: "Christianity",
      joined: DateTime.now(),
    ),
    Student(
      firstName: "John",
      lastName: "Doe",
      gender: "Male",
      image: "assets/images/watch man.jpg",
      id: "Info 13",
      level: 200,
      location: "Accord",
      amount: 50000,
      available: false,
      origin: "Ebonyi",
      denomination: "Christ Apostolic Church",
      hobby: "Singing and dancing",
      ageRange: "23 - 30",
      religion: "Christianity",
      joined: DateTime.now(),
    ),
    Student(
      firstName: "John",
      lastName: "Doe",
      gender: "Male",
      image: "assets/images/watch man.jpg",
      id: "Info 14",
      level: 500,
      location: "Kofesu",
      amount: 40000,
      available: false,
      origin: "Ebonyi",
      denomination: "Christ Apostolic Church",
      hobby: "Singing and dancing",
      ageRange: "15 - 20",
      religion: "Christianity",
      joined: DateTime.now(),
      collaboratedRoommates: 9,
      rentedHostels: 3,
      profileViews: 48,
      searchAppearances: 19,
    )
  ];
});

final StateProvider<List<String>> roomTypesProvider = StateProvider((ref) => [
      "Self Contained",
      "One-Room",
      "Face-To-Face",
      "2 Bedrooms Flat",
      "3 Bedrooms Flat",
    ]);

final StateProvider<List<String>> locationProvider = StateProvider((ref) => [
      "Kofesu",
      "Camp",
      "Accord",
      "Harmony",
      "Agbede",
      "Oluwo",
      "Isolu",
      "Funis"
    ]);

final StateProvider<List<String>> banksProvider = StateProvider((ref) => [
      "Kofesu",
      "Camp",
      "Accord",
      "Harmony",
      "Agbede",
      "Oluwo",
      "Isolu",
      "Funis"
    ]);

final StateProvider<List<NotificationData>> notificationsProvider =
    StateProvider((ref) {
  User sender = const User(
    id: "id",
    image: "assets/images/watch man.jpg",
    firstName: "John",
    lastName: "Doe",
    email: "johndoe@mail.com",
  );

  return [
    NotificationData(
      sender: sender,
      timestamp: DateTime.now(),
      message:
          "Lorem ipsum dolor sit amet, consectetur. Nam ut cursus ipsum dolor sit amet...",
    ),
    NotificationData(
      sender: sender,
      timestamp: DateTime.now(),
      message:
          "Lorem ipsum dolor sit amet, consectetur. Nam ut cursus ipsum dolor sit amet...",
    ),
    NotificationData(
      sender: sender,
      timestamp: DateTime.now(),
      message:
          "Lorem ipsum dolor sit amet, consectetur. Nam ut cursus ipsum dolor sit amet...",
    ),
    NotificationData(
      sender: sender,
      timestamp: DateTime.now(),
      message:
          "Lorem ipsum dolor sit amet, consectetur. Nam ut cursus ipsum dolor sit amet...",
    ),
    NotificationData(
      sender: sender,
      timestamp: DateTime.now(),
      message:
          "Lorem ipsum dolor sit amet, consectetur. Nam ut cursus ipsum dolor sit amet...",
    ),
    NotificationData(
      sender: sender,
      timestamp: DateTime.now(),
      message:
          "Lorem ipsum dolor sit amet, consectetur. Nam ut cursus ipsum dolor sit amet...",
    ),
    NotificationData(
      sender: sender,
      timestamp: DateTime.now(),
      message:
          "Lorem ipsum dolor sit amet, consectetur. Nam ut cursus ipsum dolor sit amet...",
    ),
    NotificationData(
      sender: sender,
      timestamp: DateTime.now(),
      message:
          "Lorem ipsum dolor sit amet, consectetur. Nam ut cursus ipsum dolor sit amet...",
    ),
  ];
});

final StateProvider<List<Receipt>> receiptsProvider = StateProvider(
  (ref) => [
    Receipt(
      timestamp: DateTime.now(),
      studentName: "Adedigba Rejoice",
      hostel: "Manchester Hostel",
      id: "12345",
      amountInWords: "One Hundred Thousand Naira (NGN 100,000)",
      landOwnerName: "Adeyemi Julius",
      reference: "202384024BG",
    ),
    Receipt(
      timestamp: DateTime.now(),
      studentName: "Adedigba Rejoice",
      hostel: "Manchester Hostel",
      id: "12345",
      amountInWords: "One Hundred Thousand Naira (NGN 100,000)",
      landOwnerName: "Adeyemi Julius",
      reference: "202384024BG",
    ),
    Receipt(
      timestamp: DateTime.now(),
      studentName: "Adedigba Rejoice",
      hostel: "Manchester Hostel",
      id: "12345",
      amountInWords: "One Hundred Thousand Naira (NGN 100,000)",
      landOwnerName: "Adeyemi Julius",
      reference: "202384024BG",
    )
  ],
);

final StateProvider<List<Transaction>> studentTransactionsProvider =
    StateProvider(
  (ref) => [
    Transaction(
      timestamp: DateTime.now(),
      type: TransactionType.credit,
      purpose: "Top-up Wallet",
      amount: 150000,
      status: TransactionStatus.success,
      receiver: "AKINWOYE OLUWAPELUMI",
      bankName: "First Bank of Nigeria",
      accountNumber: "3130201234",
      paymentID: "791798480928989DE",
    ),
    Transaction(
      timestamp: DateTime.now(),
      purpose: "Top-up Wallet",
      type: TransactionType.credit,
      amount: 100000,
      status: TransactionStatus.failed,
      receiver: "AKINWOYE OLUWAPELUMI",
      bankName: "First Bank of Nigeria",
      accountNumber: "3130201234",
      paymentID: "791798480928989DE",
    ),
    Transaction(
      timestamp: DateTime.now(),
      purpose: "Hostel Payment",
      type: TransactionType.debit,
      amount: 90000,
      receiver: "AKINWOYE OLUWAPELUMI",
      status: TransactionStatus.pending,
      paymentID: "791798480928989DE",
    ),
    Transaction(
      timestamp: DateTime.now(),
      purpose: "Top-up Wallet",
      type: TransactionType.credit,
      amount: 150000,
      status: TransactionStatus.success,
      receiver: "AKINWOYE OLUWAPELUMI",
      bankName: "First Bank of Nigeria",
      accountNumber: "3130201234",
      paymentID: "791798480928989DE",
    ),
    Transaction(
      timestamp: DateTime.now(),
      purpose: "Top-up Wallet",
      type: TransactionType.credit,
      amount: 100000,
      status: TransactionStatus.failed,
      receiver: "AKINWOYE OLUWAPELUMI",
      bankName: "First Bank of Nigeria",
      accountNumber: "3130201234",
      paymentID: "791798480928989DE",
    ),
    Transaction(
      timestamp: DateTime.now(),
      purpose: "Hostel Payment",
      type: TransactionType.debit,
      amount: 90000,
      status: TransactionStatus.pending,
      receiver: "AKINWOYE OLUWAPELUMI",
      paymentID: "791798480928989DE",
    ),
    Transaction(
      timestamp: DateTime.now(),
      purpose: "Top-up Wallet",
      type: TransactionType.credit,
      amount: 150000,
      status: TransactionStatus.success,
      receiver: "AKINWOYE OLUWAPELUMI",
      bankName: "First Bank of Nigeria",
      accountNumber: "3130201234",
      paymentID: "791798480928989DE",
    ),
    Transaction(
      timestamp: DateTime.now(),
      purpose: "Top-up Wallet",
      type: TransactionType.credit,
      amount: 100000,
      status: TransactionStatus.failed,
      receiver: "AKINWOYE OLUWAPELUMI",
      bankName: "First Bank of Nigeria",
      accountNumber: "3130201234",
      paymentID: "791798480928989DE",
    ),
    Transaction(
      timestamp: DateTime.now(),
      purpose: "Hostel Payment",
      type: TransactionType.debit,
      amount: 90000,
      receiver: "AKINWOYE OLUWAPELUMI",
      status: TransactionStatus.pending,
      paymentID: "791798480928989DE",
    ),
  ],
);

final StateProvider<List<Transaction>> ownerTransactionsProvider =
    StateProvider(
  (ref) => [
    Transaction(
      timestamp: DateTime.now(),
      type: TransactionType.credit,
      purpose: "Money Received",
      amount: 150000,
      status: TransactionStatus.success,
      receiver: "AKINWOYE OLUWAPELUMI",
      hostel: "Manchester Hostel",
      paymentID: "791798480928989DE",
    ),
    Transaction(
      timestamp: DateTime.now(),
      purpose: "Money Received",
      type: TransactionType.credit,
      amount: 100000,
      status: TransactionStatus.failed,
      receiver: "AKINWOYE OLUWAPELUMI",
      hostel: "Manchester Hostel",
      paymentID: "791798480928989DE",
    ),
    Transaction(
      timestamp: DateTime.now(),
      purpose: "Withdrawal",
      type: TransactionType.debit,
      amount: 90000,
      receiver: "AKINWOYE OLUWAPELUMI",
      status: TransactionStatus.pending,
      bankName: "First Bank of Nigeria",
      accountNumber: "3130201234",
      paymentID: "791798480928989DE",
    ),
    Transaction(
      timestamp: DateTime.now(),
      purpose: "Money Received",
      type: TransactionType.credit,
      amount: 150000,
      status: TransactionStatus.success,
      receiver: "AKINWOYE OLUWAPELUMI",
      hostel: "Manchester Hostel",
      paymentID: "791798480928989DE",
    ),
    Transaction(
      timestamp: DateTime.now(),
      purpose: "Money Received",
      type: TransactionType.credit,
      amount: 100000,
      status: TransactionStatus.failed,
      receiver: "AKINWOYE OLUWAPELUMI",
      hostel: "Manchester Hostel",
      paymentID: "791798480928989DE",
    ),
    Transaction(
      timestamp: DateTime.now(),
      purpose: "Withdrawal",
      type: TransactionType.debit,
      amount: 90000,
      status: TransactionStatus.pending,
      receiver: "AKINWOYE OLUWAPELUMI",
      bankName: "First Bank of Nigeria",
      accountNumber: "3130201234",
      paymentID: "791798480928989DE",
    ),
    Transaction(
      timestamp: DateTime.now(),
      purpose: "Money Received",
      type: TransactionType.credit,
      amount: 150000,
      status: TransactionStatus.success,
      receiver: "AKINWOYE OLUWAPELUMI",
      hostel: "Manchester Hostel",
      paymentID: "791798480928989DE",
    ),
    Transaction(
      timestamp: DateTime.now(),
      purpose: "Money Received",
      type: TransactionType.credit,
      amount: 100000,
      status: TransactionStatus.failed,
      receiver: "AKINWOYE OLUWAPELUMI",
      hostel: "Manchester Hostel",
      paymentID: "791798480928989DE",
    ),
    Transaction(
      timestamp: DateTime.now(),
      purpose: "Withdrawal",
      type: TransactionType.debit,
      amount: 90000,
      receiver: "AKINWOYE OLUWAPELUMI",
      status: TransactionStatus.pending,
      bankName: "First Bank of Nigeria",
      accountNumber: "3130201234",
      paymentID: "791798480928989DE",
    ),
  ],
);

final StateProvider<double> expensesProvider = StateProvider((ref) => 65000);

final StateProvider<double> walletProvider = StateProvider((ref) => 65000);
