import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:my_hostel/components/hostel_info.dart';
import 'package:my_hostel/components/landowner.dart';
import 'package:my_hostel/components/room_details.dart';
import 'package:my_hostel/components/roommate_info.dart';

import 'package:my_hostel/components/student.dart';

final StateProvider<bool> hasInitializedProvider =
    StateProvider((ref) => false);

final StateProvider<bool> hasMessagesProvider = StateProvider((ref) => false);

final StateProvider<bool> hasNotificationProvider =
    StateProvider((ref) => false);

final StateProvider<Student> studentProvider = StateProvider(
  (ref) => const Student(
    id: "",
    image: "assets/images/watch man.jpg",
    firstName: "Doe",
    lastName: "John",
    email: "johndoe@mail.com",
    gender: "Male",
  ),
);

final StateProvider<int> dashboardTabIndexProvider = StateProvider((ref) => 0);

final StateProvider<List<HostelInfo>> acquiredHostelsProvider =
    StateProvider((ref) => [
          HostelInfo(
            id: "1",
            name: "Manchester Hostel Askj",
            image: "assets/images/street.jpg",
            bedrooms: 1,
            bathrooms: 1,
            area: 2500,
            price: 100000,
            address: "Harmony Estate",
            description:
                "Lorem ipsum dolor sit amet, consectetur. Nam utcurs usipsum dolor sit amet. "
                "Lorem ipsum dolor sit amet, consectetur.",
            rules: const [
              "Lorem ipsum dolor sit amet, consectetur.",
              "Nam utcurs usipsum dolor sit amet.",
              "Lorem ipsum dolor sit amet, consectetur.",
              "Nam utcurs usipsum dolor sit amet.",
              "Lorem ipsum dolor sit amet, consectetur. Nam utcurs usipsum dolor sit amet."
            ],
            hostelFacilities: const [
              "Light",
              "Water",
              "Security",
              "None",
              "Light",
              "Water",
              "Security",
            ],
            roomsLeft: const [
              RoomInfo(
                name: "Room 1",
                facilities: [
                  "Light",
                  "Water",
                  "Security",
                  "None",
                ],
                id: "Room 1 ID",
                media: [
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                ],
                price: 100000,
              ),
              RoomInfo(
                name: "Room 2",
                facilities: [
                  "Light",
                  "Water",
                  "Security",
                  "None",
                ],
                id: "Room 2 ID",
                media: [
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                ],
                price: 100000,
              ),
              RoomInfo(
                name: "Room 3",
                facilities: [
                  "Light",
                  "Water",
                  "Security",
                  "None",
                ],
                id: "Room 3 ID",
                media: [
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                ],
                price: 100000,
              ),
              RoomInfo(
                name: "Room 4",
                facilities: [
                  "Light",
                  "Water",
                  "Security",
                  "None",
                ],
                id: "Room 4 ID",
                media: [
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                ],
                price: 100000,
              ),
              RoomInfo(
                name: "Room 5",
                facilities: [
                  "Light",
                  "Water",
                  "Security",
                  "None",
                ],
                id: "Room 5 ID",
                media: [
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                ],
                price: 100000,
              )
            ],
            media: const [
              "assets/images/street.jpg",
              "assets/images/street.jpg",
              "assets/images/street.jpg",
              "assets/images/street.jpg",
              "assets/images/street.jpg",
              "assets/images/street.jpg",
              "assets/images/street.jpg",
              "assets/images/street.jpg",
              "assets/images/street.jpg",
            ],
            owner: Landowner(
              id: "12",
              image: "assets/images/watch man.jpg",
              lastName: "Julius",
              firstName: "Adeyemi",
              verified: true,
              ratings: 3.5,
              contact: "+2348012345678",
              totalRated: 234,
              dateJoined: DateTime.now(),
              address: "Ibadan, Nigeria",
            ),
          ),
          HostelInfo(
            id: "2",
            name: "Liverpool Hostel",
            image: "assets/images/street.jpg",
            bedrooms: 1,
            bathrooms: 1,
            area: 2500,
            price: 100000,
            address: "Harmony Estate",
            description:
                "Lorem ipsum dolor sit amet, consectetur. Nam utcurs usipsum dolor sit amet. "
                "Lorem ipsum dolor sit amet, consectetur.",
            rules: const [
              "Lorem ipsum dolor sit amet, consectetur.",
              "Nam utcurs usipsum dolor sit amet.",
              "Lorem ipsum dolor sit amet, consectetur.",
              "Nam utcurs usipsum dolor sit amet.",
              "Lorem ipsum dolor sit amet, consectetur. Nam utcurs usipsum dolor sit amet."
            ],
            roomsLeft: const [
              RoomInfo(
                name: "Room 1",
                facilities: [
                  "Light",
                  "Water",
                  "Security",
                  "None",
                ],
                id: "Room 1 ID",
                media: [
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                ],
                price: 100000,
              ),
              RoomInfo(
                name: "Room 2",
                facilities: [
                  "Light",
                  "Water",
                  "Security",
                  "None",
                ],
                id: "Room 2 ID",
                media: [
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                ],
                price: 100000,
              ),
              RoomInfo(
                name: "Room 3",
                facilities: [
                  "Light",
                  "Water",
                  "Security",
                  "None",
                ],
                id: "Room 3 ID",
                media: [
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                ],
                price: 100000,
              ),
              RoomInfo(
                name: "Room 4",
                facilities: [
                  "Light",
                  "Water",
                  "Security",
                  "None",
                ],
                id: "Room 4 ID",
                media: [
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                ],
                price: 100000,
              ),
              RoomInfo(
                name: "Room 5",
                facilities: [
                  "Light",
                  "Water",
                  "Security",
                  "None",
                ],
                id: "Room 5 ID",
                media: [
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                ],
                price: 100000,
              )
            ],
            hostelFacilities: const [
              "Light",
              "Water",
              "Security",
              "None",
              "Light",
              "Water",
              "Security",
            ],
            media: const [
              "assets/images/street.jpg",
              "assets/images/street.jpg",
              "assets/images/street.jpg",
              "assets/images/street.jpg",
              "assets/images/street.jpg",
              "assets/images/street.jpg",
              "assets/images/street.jpg",
              "assets/images/street.jpg",
              "assets/images/street.jpg",
            ],
            owner: Landowner(
              id: "12",
              image: "assets/images/watch man.jpg",
              lastName: "Julius",
              firstName: "Adeyemi",
              verified: true,
              ratings: 3.5,
              contact: "+2348012345678",
              totalRated: 234,
              dateJoined: DateTime.now(),
              address: "Ibadan, Nigeria",
            ),
          ),
          HostelInfo(
            id: "3",
            name: "Scotland",
            image: "assets/images/street.jpg",
            bedrooms: 1,
            bathrooms: 1,
            area: 2500,
            price: 100000,
            address: "Harmony Estate",
            description:
                "Lorem ipsum dolor sit amet, consectetur. Nam utcurs usipsum dolor sit amet. "
                "Lorem ipsum dolor sit amet, consectetur.",
            rules: const [
              "Lorem ipsum dolor sit amet, consectetur.",
              "Nam utcurs usipsum dolor sit amet.",
              "Lorem ipsum dolor sit amet, consectetur.",
              "Nam utcurs usipsum dolor sit amet.",
              "Lorem ipsum dolor sit amet, consectetur. Nam utcurs usipsum dolor sit amet."
            ],
            hostelFacilities: const [
              "Light",
              "Water",
              "Security",
              "None",
              "Light",
              "Water",
              "Security",
            ],
            roomsLeft: const [
              RoomInfo(
                name: "Room 1",
                facilities: [
                  "Light",
                  "Water",
                  "Security",
                  "None",
                ],
                id: "Room 1 ID",
                media: [
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                ],
                price: 100000,
              ),
              RoomInfo(
                name: "Room 2",
                facilities: [
                  "Light",
                  "Water",
                  "Security",
                  "None",
                ],
                id: "Room 2 ID",
                media: [
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                ],
                price: 100000,
              ),
              RoomInfo(
                name: "Room 3",
                facilities: [
                  "Light",
                  "Water",
                  "Security",
                  "None",
                ],
                id: "Room 3 ID",
                media: [
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                ],
                price: 100000,
              ),
              RoomInfo(
                name: "Room 4",
                facilities: [
                  "Light",
                  "Water",
                  "Security",
                  "None",
                ],
                id: "Room 4 ID",
                media: [
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                ],
                price: 100000,
              ),
              RoomInfo(
                name: "Room 5",
                facilities: [
                  "Light",
                  "Water",
                  "Security",
                  "None",
                ],
                id: "Room 5 ID",
                media: [
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                ],
                price: 100000,
              )
            ],
            media: const [
              "assets/images/street.jpg",
              "assets/images/street.jpg",
              "assets/images/street.jpg",
              "assets/images/street.jpg",
              "assets/images/street.jpg",
              "assets/images/street.jpg",
              "assets/images/street.jpg",
              "assets/images/street.jpg",
              "assets/images/street.jpg",
            ],
            owner: Landowner(
              id: "12",
              image: "assets/images/watch man.jpg",
              lastName: "Julius",
              firstName: "Adeyemi",
              verified: true,
              ratings: 3.5,
              contact: "+2348012345678",
              totalRated: 234,
              dateJoined: DateTime.now(),
              address: "Ibadan, Nigeria",
            ),
          ),
          HostelInfo(
            id: "4",
            name: "Grace Ville",
            image: "assets/images/street.jpg",
            bedrooms: 1,
            bathrooms: 1,
            area: 2500,
            price: 100000,
            address: "Harmony Estate",
            description:
                "Lorem ipsum dolor sit amet, consectetur. Nam utcurs usipsum dolor sit amet. "
                "Lorem ipsum dolor sit amet, consectetur.",
            rules: const [
              "Lorem ipsum dolor sit amet, consectetur.",
              "Nam utcurs usipsum dolor sit amet.",
              "Lorem ipsum dolor sit amet, consectetur.",
              "Nam utcurs usipsum dolor sit amet.",
              "Lorem ipsum dolor sit amet, consectetur. Nam utcurs usipsum dolor sit amet."
            ],
            hostelFacilities: const [
              "Light",
              "Water",
              "Security",
              "None",
              "Light",
              "Water",
              "Security",
            ],
            roomsLeft: const [
              RoomInfo(
                name: "Room 1",
                facilities: [
                  "Light",
                  "Water",
                  "Security",
                  "None",
                ],
                id: "Room 1 ID",
                media: [
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                ],
                price: 100000,
              ),
              RoomInfo(
                name: "Room 2",
                facilities: [
                  "Light",
                  "Water",
                  "Security",
                  "None",
                ],
                id: "Room 2 ID",
                media: [
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                ],
                price: 100000,
              ),
              RoomInfo(
                name: "Room 3",
                facilities: [
                  "Light",
                  "Water",
                  "Security",
                  "None",
                ],
                id: "Room 3 ID",
                media: [
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                ],
                price: 100000,
              ),
              RoomInfo(
                name: "Room 4",
                facilities: [
                  "Light",
                  "Water",
                  "Security",
                  "None",
                ],
                id: "Room 4 ID",
                media: [
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                ],
                price: 100000,
              ),
              RoomInfo(
                name: "Room 5",
                facilities: [
                  "Light",
                  "Water",
                  "Security",
                  "None",
                ],
                id: "Room 5 ID",
                media: [
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                ],
                price: 100000,
              )
            ],
            media: const [
              "assets/images/street.jpg",
              "assets/images/street.jpg",
              "assets/images/street.jpg",
              "assets/images/street.jpg",
              "assets/images/street.jpg",
              "assets/images/street.jpg",
              "assets/images/street.jpg",
              "assets/images/street.jpg",
              "assets/images/street.jpg",
            ],
            owner: Landowner(
              id: "12",
              image: "assets/images/watch man.jpg",
              lastName: "Julius",
              firstName: "Adeyemi",
              verified: true,
              ratings: 3.5,
              contact: "+2348012345678",
              totalRated: 234,
              dateJoined: DateTime.now(),
              address: "Ibadan, Nigeria",
            ),
          )
        ]);
final StateProvider<List<RoommateInfo>> acquiredRoommatesProvider =
    StateProvider((ref) {
  Student student = const Student(
    firstName: "John",
    lastName: "Doe",
    gender: "Male",
    image: "assets/images/watch man.jpg",
  );

  return [
    RoommateInfo(
      id: "Info 1",
      student: student,
      level: 100,
      location: "Harmony",
      amount: 50000,
      available: true,
      origin: "Ebonyi",
      denomination: "Christ Apostolic Church",
      hobby: "Singing and dancing",
      ageRange: "23 - 30",
      religion: "Christianity",
    ),
    RoommateInfo(
      id: "Info 2",
      student: student,
      level: 300,
      location: "Isolu",
      amount: 75000,
      available: true,
      origin: "Ebonyi",
      denomination: "Christ Apostolic Church",
      hobby: "Singing and dancing",
      ageRange: "23 - 30",
      religion: "Christianity",
    ),
    RoommateInfo(
      id: "Info 3",
      student: student,
      level: 200,
      location: "Accord",
      amount: 50000,
      available: false,
      origin: "Ebonyi",
      denomination: "Christ Apostolic Church",
      hobby: "Singing and dancing",
      ageRange: "23 - 30",
      religion: "Christianity",
    ),
    RoommateInfo(
      id: "Info 4",
      student: student,
      level: 500,
      location: "Kofesu",
      amount: 40000,
      available: false,
      origin: "Ebonyi",
      denomination: "Christ Apostolic Church",
      hobby: "Singing and dancing",
      ageRange: "23 - 30",
      religion: "Christianity",
    )
  ];
});

final StateProvider<List<HostelInfo>> availableHostelsProvider =
    StateProvider((ref) => [
          HostelInfo(
            id: "11",
            name: "Manchester Hostel Askj",
            image: "assets/images/street.jpg",
            bedrooms: 1,
            bathrooms: 1,
            area: 2500,
            price: 100000,
            address: "Harmony Estate",
            description:
                "Lorem ipsum dolor sit amet, consectetur. Nam utcurs usipsum dolor sit amet. "
                "Lorem ipsum dolor sit amet, consectetur.",
            rules: const [
              "Lorem ipsum dolor sit amet, consectetur.",
              "Nam utcurs usipsum dolor sit amet.",
              "Lorem ipsum dolor sit amet, consectetur.",
              "Nam utcurs usipsum dolor sit amet.",
              "Lorem ipsum dolor sit amet, consectetur. Nam utcurs usipsum dolor sit amet."
            ],
            hostelFacilities: const [
              "Light",
              "Water",
              "Security",
              "None",
              "Light",
              "Water",
              "Security",
            ],
            roomsLeft: const [
              RoomInfo(
                name: "Room 1",
                facilities: [
                  "Light",
                  "Water",
                  "Security",
                  "None",
                ],
                id: "Room 1 ID",
                media: [
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                ],
                price: 100000,
              ),
              RoomInfo(
                name: "Room 2",
                facilities: [
                  "Light",
                  "Water",
                  "Security",
                  "None",
                ],
                id: "Room 2 ID",
                media: [
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                ],
                price: 100000,
              ),
              RoomInfo(
                name: "Room 3",
                facilities: [
                  "Light",
                  "Water",
                  "Security",
                  "None",
                ],
                id: "Room 3 ID",
                media: [
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                ],
                price: 100000,
              ),
              RoomInfo(
                name: "Room 4",
                facilities: [
                  "Light",
                  "Water",
                  "Security",
                  "None",
                ],
                id: "Room 4 ID",
                media: [
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                ],
                price: 100000,
              ),
              RoomInfo(
                name: "Room 5",
                facilities: [
                  "Light",
                  "Water",
                  "Security",
                  "None",
                ],
                id: "Room 5 ID",
                media: [
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                ],
                price: 100000,
              )
            ],
            media: const [
              "assets/images/street.jpg",
              "assets/images/street.jpg",
              "assets/images/street.jpg",
              "assets/images/street.jpg",
              "assets/images/street.jpg",
              "assets/images/street.jpg",
              "assets/images/street.jpg",
              "assets/images/street.jpg",
              "assets/images/street.jpg",
            ],
            owner: Landowner(
              id: "12",
              image: "assets/images/watch man.jpg",
              lastName: "Julius",
              firstName: "Adeyemi",
              verified: true,
              ratings: 3.5,
              contact: "+2348012345678",
              totalRated: 234,
              dateJoined: DateTime.now(),
              address: "Ibadan, Nigeria",
            ),
          ),
          HostelInfo(
            id: "12",
            name: "Liverpool Hostel",
            image: "assets/images/street.jpg",
            bedrooms: 1,
            bathrooms: 1,
            area: 2500,
            price: 100000,
            address: "Harmony Estate",
            description:
                "Lorem ipsum dolor sit amet, consectetur. Nam utcurs usipsum dolor sit amet. "
                "Lorem ipsum dolor sit amet, consectetur.",
            rules: const [
              "Lorem ipsum dolor sit amet, consectetur.",
              "Nam utcurs usipsum dolor sit amet.",
              "Lorem ipsum dolor sit amet, consectetur.",
              "Nam utcurs usipsum dolor sit amet.",
              "Lorem ipsum dolor sit amet, consectetur. Nam utcurs usipsum dolor sit amet."
            ],
            roomsLeft: const [
              RoomInfo(
                name: "Room 1",
                facilities: [
                  "Light",
                  "Water",
                  "Security",
                  "None",
                ],
                id: "Room 1 ID",
                media: [
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                ],
                price: 100000,
              ),
              RoomInfo(
                name: "Room 2",
                facilities: [
                  "Light",
                  "Water",
                  "Security",
                  "None",
                ],
                id: "Room 2 ID",
                media: [
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                ],
                price: 100000,
              ),
              RoomInfo(
                name: "Room 3",
                facilities: [
                  "Light",
                  "Water",
                  "Security",
                  "None",
                ],
                id: "Room 3 ID",
                media: [
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                ],
                price: 100000,
              ),
              RoomInfo(
                name: "Room 4",
                facilities: [
                  "Light",
                  "Water",
                  "Security",
                  "None",
                ],
                id: "Room 4 ID",
                media: [
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                ],
                price: 100000,
              ),
              RoomInfo(
                name: "Room 5",
                facilities: [
                  "Light",
                  "Water",
                  "Security",
                  "None",
                ],
                id: "Room 5 ID",
                media: [
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                ],
                price: 100000,
              )
            ],
            hostelFacilities: const [
              "Light",
              "Water",
              "Security",
              "None",
              "Light",
              "Water",
              "Security",
            ],
            media: const [
              "assets/images/street.jpg",
              "assets/images/street.jpg",
              "assets/images/street.jpg",
              "assets/images/street.jpg",
              "assets/images/street.jpg",
              "assets/images/street.jpg",
              "assets/images/street.jpg",
              "assets/images/street.jpg",
              "assets/images/street.jpg",
            ],
            owner: Landowner(
              id: "12",
              image: "assets/images/watch man.jpg",
              lastName: "Julius",
              firstName: "Adeyemi",
              verified: true,
              ratings: 3.5,
              contact: "+2348012345678",
              totalRated: 234,
              dateJoined: DateTime.now(),
              address: "Ibadan, Nigeria",
            ),
          ),
          HostelInfo(
            id: "13",
            name: "Scotland",
            image: "assets/images/street.jpg",
            bedrooms: 1,
            bathrooms: 1,
            area: 2500,
            price: 100000,
            address: "Harmony Estate",
            description:
                "Lorem ipsum dolor sit amet, consectetur. Nam utcurs usipsum dolor sit amet. "
                "Lorem ipsum dolor sit amet, consectetur.",
            rules: const [
              "Lorem ipsum dolor sit amet, consectetur.",
              "Nam utcurs usipsum dolor sit amet.",
              "Lorem ipsum dolor sit amet, consectetur.",
              "Nam utcurs usipsum dolor sit amet.",
              "Lorem ipsum dolor sit amet, consectetur. Nam utcurs usipsum dolor sit amet."
            ],
            roomsLeft: const [
              RoomInfo(
                name: "Room 1",
                facilities: [
                  "Light",
                  "Water",
                  "Security",
                  "None",
                ],
                id: "Room 1 ID",
                media: [
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                ],
                price: 100000,
              ),
              RoomInfo(
                name: "Room 2",
                facilities: [
                  "Light",
                  "Water",
                  "Security",
                  "None",
                ],
                id: "Room 2 ID",
                media: [
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                ],
                price: 100000,
              ),
              RoomInfo(
                name: "Room 3",
                facilities: [
                  "Light",
                  "Water",
                  "Security",
                  "None",
                ],
                id: "Room 3 ID",
                media: [
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                ],
                price: 100000,
              ),
              RoomInfo(
                name: "Room 4",
                facilities: [
                  "Light",
                  "Water",
                  "Security",
                  "None",
                ],
                id: "Room 4 ID",
                media: [
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                ],
                price: 100000,
              ),
              RoomInfo(
                name: "Room 5",
                facilities: [
                  "Light",
                  "Water",
                  "Security",
                  "None",
                ],
                id: "Room 5 ID",
                media: [
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                ],
                price: 100000,
              )
            ],
            hostelFacilities: const [
              "Light",
              "Water",
              "Security",
              "None",
              "Light",
              "Water",
              "Security",
            ],
            media: const [
              "assets/images/street.jpg",
              "assets/images/street.jpg",
              "assets/images/street.jpg",
              "assets/images/street.jpg",
              "assets/images/street.jpg",
              "assets/images/street.jpg",
              "assets/images/street.jpg",
              "assets/images/street.jpg",
              "assets/images/street.jpg",
            ],
            owner: Landowner(
              id: "12",
              image: "assets/images/watch man.jpg",
              lastName: "Julius",
              firstName: "Adeyemi",
              verified: true,
              ratings: 3.5,
              contact: "+2348012345678",
              totalRated: 234,
              dateJoined: DateTime.now(),
              address: "Ibadan, Nigeria",
            ),
          ),
          HostelInfo(
            id: "14",
            name: "Grace Ville",
            image: "assets/images/street.jpg",
            bedrooms: 1,
            bathrooms: 1,
            area: 2500,
            price: 100000,
            address: "Harmony Estate",
            description:
                "Lorem ipsum dolor sit amet, consectetur. Nam utcurs usipsum dolor sit amet. "
                "Lorem ipsum dolor sit amet, consectetur.",
            rules: const [
              "Lorem ipsum dolor sit amet, consectetur.",
              "Nam utcurs usipsum dolor sit amet.",
              "Lorem ipsum dolor sit amet, consectetur.",
              "Nam utcurs usipsum dolor sit amet.",
              "Lorem ipsum dolor sit amet, consectetur. Nam utcurs usipsum dolor sit amet."
            ],
            roomsLeft: const [
              RoomInfo(
                name: "Room 1",
                facilities: [
                  "Light",
                  "Water",
                  "Security",
                  "None",
                ],
                id: "Room 1 ID",
                media: [
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                ],
                price: 100000,
              ),
              RoomInfo(
                name: "Room 2",
                facilities: [
                  "Light",
                  "Water",
                  "Security",
                  "None",
                ],
                id: "Room 2 ID",
                media: [
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                ],
                price: 100000,
              ),
              RoomInfo(
                name: "Room 3",
                facilities: [
                  "Light",
                  "Water",
                  "Security",
                  "None",
                ],
                id: "Room 3 ID",
                media: [
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                ],
                price: 100000,
              ),
              RoomInfo(
                name: "Room 4",
                facilities: [
                  "Light",
                  "Water",
                  "Security",
                  "None",
                ],
                id: "Room 4 ID",
                media: [
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                ],
                price: 100000,
              ),
              RoomInfo(
                name: "Room 5",
                facilities: [
                  "Light",
                  "Water",
                  "Security",
                  "None",
                ],
                id: "Room 5 ID",
                media: [
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                  "assets/images/street.jpg",
                ],
                price: 100000,
              )
            ],
            hostelFacilities: const [
              "Light",
              "Water",
              "Security",
              "None",
              "Light",
              "Water",
              "Security",
            ],
            media: const [
              "assets/images/street.jpg",
              "assets/images/street.jpg",
              "assets/images/street.jpg",
              "assets/images/street.jpg",
              "assets/images/street.jpg",
              "assets/images/street.jpg",
              "assets/images/street.jpg",
              "assets/images/street.jpg",
              "assets/images/street.jpg",
            ],
            owner: Landowner(
              id: "12",
              image: "assets/images/watch man.jpg",
              lastName: "Julius",
              firstName: "Adeyemi",
              verified: true,
              ratings: 3.5,
              contact: "+2348012345678",
              totalRated: 234,
              dateJoined: DateTime.now(),
              address: "Ibadan, Nigeria",
            ),
          )
        ]);
final StateProvider<List<RoommateInfo>> availableRoommatesProvider =
    StateProvider((ref) {
  Student student = const Student(
    firstName: "John",
    lastName: "Doe",
    gender: "Male",
    image: "assets/images/watch man.jpg",
  );

  return [
    RoommateInfo(
      id: "Info 11",
      student: student,
      level: 100,
      location: "Harmony",
      amount: 50000,
      available: true,
      origin: "Ebonyi",
      denomination: "Christ Apostolic Church",
      hobby: "Singing and dancing",
      ageRange: "23 - 30",
      religion: "Christianity",
    ),
    RoommateInfo(
      id: "Info 12",
      student: student,
      level: 300,
      location: "Isolu",
      amount: 75000,
      available: true,
      origin: "Ebonyi",
      denomination: "Christ Apostolic Church",
      hobby: "Singing and dancing",
      ageRange: "23 - 30",
      religion: "Christianity",
    ),
    RoommateInfo(
      id: "Info 13",
      student: student,
      level: 200,
      location: "Accord",
      amount: 50000,
      available: false,
      origin: "Ebonyi",
      denomination: "Christ Apostolic Church",
      hobby: "Singing and dancing",
      ageRange: "23 - 30",
      religion: "Christianity",
    ),
    RoommateInfo(
      id: "Info 14",
      student: student,
      level: 500,
      location: "Kofesu",
      amount: 40000,
      available: false,
      origin: "Ebonyi",
      denomination: "Christ Apostolic Church",
      hobby: "Singing and dancing",
      ageRange: "23 - 30",
      religion: "Christianity",
    )
  ];
});

final StateProvider<List<String>> roomTypesProvider = StateProvider((ref) => [
      "Self Contained",
      "One-Room",
      "Face-To-Face",
      "2 Bedrooms Flat",
      "3 Bedrooms Flat",
    ]);

final StateProvider<List<String>> locationProvider = StateProvider((ref) => [
      "Kofesu",
      "Camp",
      "Accord",
      "Harmony",
      "Agbede",
      "Oluwo",
      "Isolu",
      "Funis"
    ]);
