name: my_hostel
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  dio:
  file_picker:
  intl:
  clipboard:
  path_provider:
  equatable:
  flutter_boxicons:
  flutter_screenutil:
  flutter_spinkit:
  connectivity_plus:
  cached_network_image:
  flutter_launcher_icons:
  flutter_native_splash:
  chatview:
  timeago:
  shared_preferences:
  flutter_svg:
  transparent_image:
  helpers:
  socket_io_client:
  chat_bubbles:
  permission_handler:
  go_router:
  flutter_riverpod:
  animated_switcher_plus:
  flex_color_scheme:
  flutter_staggered_animations:
  skeletonizer:
  flutter_lazy_listview:
  fluttertoast:
  flutter_rating_stars:
  url_launcher:
  flutter_otp_text_field:
  dropdown_button2:
  badges:
  photo_view:
  animated_text_kit:
  get_thumbnail_video:

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.1

flutter_native_splash:
  color: "#064997"
  android: true
  ios: true

flutter_icons:
  image_path_android: "assets/images/oostel.png"
  image_path_ios: "assets/images/oostel.png"
  android: true
  ios: true
  adaptive_icon_background: "#064997"
  adaptive_icon_foreground: "assets/images/oostel.png"
  min_sdk_android: 29
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
     - assets/images/

  fonts:
    - family: WorkSans
      fonts:
        - asset: assets/fonts/WorkSans-Black.ttf
        - asset: assets/fonts/WorkSans-Bold.ttf
        - asset: assets/fonts/WorkSans-Italic.ttf
        - asset: assets/fonts/WorkSans-Light.ttf
        - asset: assets/fonts/WorkSans-Medium.ttf
        - asset: assets/fonts/WorkSans-Regular.ttf
        - asset: assets/fonts/WorkSans-Thin.ttf
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Black.ttf
        - asset: assets/fonts/Inter-Bold.ttf
        - asset: assets/fonts/Inter-ExtraBold.ttf
        - asset: assets/fonts/Inter-Light.ttf
        - asset: assets/fonts/Inter-ExtraLight.ttf
        - asset: assets/fonts/Inter-Medium.ttf
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-SemiBold.ttf
        - asset: assets/fonts/Inter-Thin.ttf